apiVersion: apps/v1
kind: Deployment
metadata:
  name: template
  labels:
    app: template
spec:
  replicas: 1
  selector:
    matchLabels:
      app: template
  template:
    metadata:
      labels:
        app: template
    spec:
      imagePullSecrets:
        - name: {{ .Values.imagePullSecrets }}
      containers:
        - name: template
          image: {{ .Values.image }}
          imagePullPolicy: Always
          env:
            {{- range .Values.environments }}
            - name: {{ .name }}
              value: "{{ .value }}"
            {{- end }}
          ports:
            - containerPort: 8080
              name: http-app
              protocol: TCP
