apiVersion: v1
kind: Service
metadata:
  name: template-service
spec:
  type: ClusterIP
  selector:
    app: template
  ports:
    - name: http-app
      port: 8080
      protocol: TCP
      targetPort: http-app
